### ISSUE TITLE
Anyway to fix IAuraSyncDevice.Apply take very long time to execute?

### ISSUE THREAD

**Issue by Desz01ate** [DarthAffe/RGB.NET#186]
I have an application that send a very frequent updates to RGB devices (like every 16 ms or so)
for Razer sdk everything is working fine but Asus sdk seems to be very slow to apply effect to devices which cause a noticeable stutter effect.

**Comment by DarthAffe** [comment]
Sadly this is nothing that can be fixed on my side. Depending on what is causing the delay on asus-side you might be able to get better update rates by using openrgb (https://gitlab.com/CalcProgrammer1/OpenRGB) instead of the official aura-sdk (this wouldn't be the case if the hardware is the limiting factor though).
diogotr7 created an provider to load openRGB-devices into RGB.NET (https://github.com/diogotr7/RGB.NET.Devices.OpenRGB).
But since i don't know your use-case it's hard to help with a specific solution.

**Comment by Desz01ate** [comment]
I agreed that no way to fix this on our side without Asus to fix their sdk, even direct access to the sdk without any abstract layer still yield atleast 4-50ms delay each time I try to apply effect (my use case is spectrum visualization which required very frequent update).
