### ISSUE TITLE
Remote interface?

### ISSUE THREAD

**Issue by starkillerOG** [DarthAffe/RGB.NET#31]
I just stumbled accros your project and it looks verry cool and promesing!
I just have a small question, will this project get an remote interface like a json interface or MQTT interface?
What I am eventually looking for is controlling the RGB lighting inside a desktop (GPU, Motherboard, RAM etc.) remoteley over the local network (wifi or LAN) through a home automation platform like HomeAssistant.

Is something like a remote interface considered for this project?

**Comment by DarthAffe** [comment]
No, something like this will never be part of this project (it's just outside the scope) - the closest thing would be the SoIP-Proivder which is an example of how to sync over an socket - but for such a specific use case it's most likely better to create something specific.
Since everything is modular you can easily create something fitting your use case.
