### ISSUE TITLE
Support for MSI MysticLight SDK

### ISSUE THREAD

**Issue by BrianLima** [DarthAffe/RGB.NET#4]
Hi @DarthAffe , i would like to request support for the MysticLight SDK By MSI. I have a MSI B350 Tomahawk Arctic that is listed as Sync compatible, so i can help you in debugging it.

https://msi.com/Landing/mystic-light-motherboard#extension

**Comment by DarthAffe** [comment]
Hey, I just took a quick look on the SDK - this seems to be not too much of an issue to implement. I hope I'm able to do this in the next one or two days.
Since I've seen you already on discord I'll get back to you there once I got something to work with.

**Comment by DarthAffe** [comment]
Closed since it's on the list and we are at it as soon as there's access to a compatible device.

**Comment by DarthAffe** [comment]
Ok thanks, I'll look into it!

**Comment by DarthAffe** [comment]
@SimoDax Do you own a device compatible with the SDK? As far as I understand your description you wasn't able to see it working so far, is that right? So far I wasn't able to find someone with a compatible device (and we tried quite a lot) since even if it's stated to be mystic light compatible on the homepage the SDK returns a always -2 (timeout) as error-code.

**Comment by SimoDax** [comment]
My hardware only supports mystic light 1, which is not compatible with the sdk. However, if you look at issue SimoDax/MSI-mystic-light-tool#1 you'll find that it actually works with compatible systems. Have you tried running as admin?

**Comment by pipe01** [comment]
Any progress on this?
