### ISSUE TITLE
Implement providers for all known RGB-SDKs/Devices

### ISSUE THREAD

**Issue by DarthAffe** [DarthAffe/RGB.NET#5]
Prepare Device-Providers for the following Companies/SDKs:
- [x] Asus Aura _(Not reliable at the moment)_
- [x] CoolerMaster
- [x] Corsair
- [ ] ~~CorsairLink~~
- [ ] Gigabyte RGB Fusion
- [x] Logitech _(Device provider is working but needs more work to completely implement device-detection)_
- [x] MSI Mythic Light
- [x] Novation
- [x] OLA (DMX)
- [ ] Phillips HUE
- [x] Razer
- [ ] Roccat
- [ ] SoundBlaster
- [x] SteelSeries

More information about the supported devices can be found [here](https://github.com/DarthAffe/RGB.NET/wiki/Supported-devices).

**Comment by Electrifide** [comment]
Hey DarthAffe, btw thanks for putting this project together.  I have an odd request... it's on the border/potentially out of the scope of this project; so if you don't want anything to do with this, no worries, I totally understand... but since I'm a degreed Electrical Engineer, if I did the "leg-work" and co-developed a small add-on to your RGB.NET SDK, maybe you'd be open to including it in the final Rev?

The oddball request I'm talking about is the olddddd-school Thermaltake Riing fans with the 3-button tactile control boxes (I know the newer TTPremium fans have already made this an obsolete "legacy" feature).  But if I made an easy-to-follow guide that uses Arduino/RaspberryPi, some simple hardware modifications to those Thermaltake controllers (tied into GPIO pins), and then developed some embedded code that would process/convert commands from higher-up .NET languages to then actually command the Thermaltake hardware to imitate as many RGB effects as possible...  

Does that sound like something you'd even be interested in?  I may develop something like it regardless for my own convenience, and could keep you in the loop if you'd rather have that instead.


Thnx again,
Dave

**Comment by DarthAffe** [comment]
Hey,
this is absolutely not out of scope! At the moment I'm not sure how to integrate such edge-case-projects (might be a own device-project containing a lot of "weird things", or a project-site describing such hacks, especially if hardware modification is included) but it'd be a waste if something like this is developed without sharing it ;-)

About the implementation I'd ask you to take a look at https://github.com/OpenLightingProject/ola. I'm using this on a raspi to control my room-light, that's why I planned to write a provider for it. But I'm not 100% sure if this servers your purpose well (I'm using it with a DMX-shield, not with gpio), but it would allow as to unify the hardware modification a bit, so that it could potentially be easily adopted to similar other hardware.

**Comment by stbatuhan** [comment]
NZXT can be implemented. There is various works with that on github.

**Comment by tylerszabo** [comment]
Hi @DarthAffe I you might consider splitting Gigabyte's RGB Fusion into Motherboard / Graphics as they have very different APIs for interacting with each (the SDK release as of 2018-02-06 only supports motherboards, but you can find the VGA library in their RGB Fusion software release).
