### ISSUE TITLE
Support for PhilipsHue

### ISSUE THREAD

**Issue by tsndr** [DarthAffe/RGB.NET#8]
I would like to see PhilipsHue support in the near future.

**Comment by DarthAffe** [comment]
Hey, Philiph HUE is already on the list (https://github.com/DarthAffe/RGB.NET/issues/5), that's why I'll close this issue for now.
Someone already experimented with it (I don't own HUE-devices that's why I can't work on that on my own), but since the low update-rate-limit made it quite useless it's on hold until the Hue Entertainment Development Kit can be used.
