### ISSUE TITLE
Corsair Memory Modules are not updated

### ISSUE THREAD

**Issue by tahnik** [DarthAffe/RGB.NET#81]
It changes all the colour of all the corsair modules except the memory. Is there a particular reason behind it?

Thanks.

**Comment by SpoinkyNL** [comment]
Hi, this is a limitation in iCUE. You can get around it by enabling full software control in your RAM's device settings.

![](https://i.imgur.com/RfFaKK0.png)

The reason this is disabled by default is because it uses a relatively high amount of CPU. When enabled, you'll see the RAM show up in RGB.NET and it works just fine.
